### PR TITLE
update to use manageiq-style

### PR DESCRIPTION
**Pull request by d-m-u**
it'd be nice to be able to run rubocop on this repo

### CODE REVIEW

**Comment by Fryguy** [comment]
Can you run `manageiq-style -i` on this repo?

**Comment by Fryguy** [comment]
@bdunne Please review.

**Comment by d-m-u** [comment]
> Can you run `manageiq-style -i` on this repo?

```
✔ ~/awesome_spawn [use_manageiq_style L|…1⚑ 1]
12:54 $ manageiq-style -i
✔ ~/awesome_spawn [use_manageiq_style L|…3⚑ 1]
```

_can_ I? sure. what was supposed to happen might be a better question though...

**Comment by Fryguy** [comment]
...and commit the changes it made? 😉

**Comment by Fryguy** [comment]
Somehow I missed merging this, but it was done in #54

**Pull request closed without merging**
