### PR TITLE
use blank? checks instead of nil and empty

### PR DESCRIPTION
**Pull request by d-m-u**
exactly what it says on the tin

@miq-bot add_label cleanup

### CODE REVIEW

**Comment by d-m-u** [comment]
@miq-bot add_label cleanup
@miq-bot assign @Fryguy

**Comment by d-m-u** [comment]
```
       +undefined method `presence' for "":String
       +Did you mean?  present?
```

**Comment by Fryguy** [comment]
active_support is not a dependency of this gem.  I believe this was intentional as we didn't think it was worth pulling in that huge gem for one or two minor methods.

**Comment by d-m-u** [comment]
cool, then you should be willing to merge this the way it is, right?

**Comment by chessbyte** [comment]
but the specs are failing on Travis

**Comment by d-m-u** [comment]
those failures have nothing to do with this change

**Comment by Fryguy** [comment]
I don't understand.  The current code is in place because blank? can't work, as blank? comes from active support, which isn't a dependency.  I'm actually surprised the tests are paying on 2.4

**Comment by d-m-u** [comment]
oh, right. hilarious. well then, feel free to close.

**Comment by d-m-u** [comment]
moving out of private conversation: 
```
pry(AwesomeSpawn)> "".method(:blank?).source_location
=> ["/Users/drewmu/.rvm/gems/ruby-2.5.8/gems/tins-1.24.1/lib/tins/xt/blank.rb", 48]
```

I think tins is a coveralls dependency which as Jason pointed out is problematic in prod.

**Pull request closed without merging**
